version: '3.8'  
services:
  mongodb-syntheticcwedb:
    image: mongo:latest
    container_name: mongodb-syntheticcwedb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
