name: Run tests and upload coverage

on:
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    env:
      USE_DUMMY_AI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install just
        run: sudo apt install just

      - name: Install pip dependencies
        run: just install

      - name: Download CWEC XML
        run: just fetch-cwe

      - name: Run tests with coverage
        run: just test-cov

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}